### ISSUE TITLE
Still using very old version of jshint, which now has out-of-memory issues at install time

### ISSUE THREAD

**Issue by djmitchella** [dsturley/grunt-linter#9]
See https://github.com/jshint/jshint/issues/1594

 This is not the case in newer versions of jshint, but grunt-linter is pinned to jshint 1.1.0, which still uses the now-big tarball of esprima.

**Comment by dsturley** [comment]
Version 0.3.3 w/ 2.4.x JSHint dependency is available on [npm](https://www.npmjs.org/package/grunt-linter)
